# FastAPI Application Configuration
app:
  name: IlamicBook API
  version: 1.0.0
  description: FastAPI backend for IlamicBook

# Server Configuration
server:
  host: 0.0.0.0
  port: 8000
  reload: true

# CORS Configuration
cors:
  origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
  credentials: true
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Content-Type
    - Authorization

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API Configuration
api:
  prefix: /api
  version: v1
  title: IlamicBook API
  description: FastAPI backend for IlamicBook 